#!/bin/sh -e

echo "<?PHP header(\"location:tmx\") ?>" > /var/www/index.php
chmod 644 /var/www/index.php
chown www-data:www-data /var/www/*
chown -R www-data:www-data /var/www/tmx

sed '/short_open_tag/s/Off/On/g' -i /etc/php5/apache2/php.ini
rm -f /etc/apache2/sites-enabled/*
ln -s /etc/apache2/sites-available/default-site /etc/apache2/sites-enabled/default-site

set +e
php5enmod mcrypt
#pecl install zip
set -e

initctl reload-configuration
service apache2 restart
sleep 1
service websockify restart
