
# - Find Net-SNMP
#
# -*- cmake -*-
#
# Find the Net-SNMP module
#
#  LEARSDK_INCLUDE_DIR - where to find Net-SNMP.h, etc.
#  LEARSDK_LIBRARIES   - List of libraries when using Net-SNMP.
#  LEARSDK_FOUND       - True if Net-SNMP found.

IF (NOT LEARSDK_VERSION)
	SET (LEARSDK_VERSION Locomate_Roadstar_arm_sdk_v16.3.PR09)
ENDIF (NOT LEARSDK_VERSION)

FIND_PATH (LEARSDK_INCLUDE_DIR dot3/lib16093.h
		   PATH_SUFFIXES ${LEARSDK_VERSION} ${LEARSDK_VERSION}/include)

SET (LEARSDK_INCLUDE_DIRS "${LEARSDK_INCLUDE_DIR}" "${LEARSDK_INCLUDE_DIR}/security" "${LEARSDK_INCLUDE_DIR}/tools" )

SET (LEARVS_NAMES vehiclesensor)
FIND_LIBRARY (LEARVS_LIBRARY
  NAMES ${LEARVS_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEARLS_NAMES locationsensor)
FIND_LIBRARY (LEARLS_LIBRARY
  NAMES ${LEARLS_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEARMC_NAMES multicaster)
FIND_LIBRARY (LEARMC_LIBRARY
  NAMES ${LEARMC_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEARSDEE_NAMES sdee)
FIND_LIBRARY (LEARSDEE_LIBRARY
  NAMES ${LEARSDEE_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEAROSSTOED_NAMES osstoed)
FIND_LIBRARY (LEAROSSTOED_LIBRARY
  NAMES ${LEAROSSTOED_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEARDOT3_NAMES dot3)
FIND_LIBRARY (LEARDOT3_LIBRARY
  NAMES ${LEARDOT3_NAMES}
  PATHS ${LEARSDK_INCLUDE_DIR}/../libs
)

SET (LEARSDK_LIBRARIES
  ${LEARVS_LIBRARY}
  ${LEARLS_LIBRARY}
  ${LEARMC_LIBRARY}
  ${LEARSDEE_LIBRARY}
  ${LEAROSSTOED_LIBRARY}
  ${LEARDOT3_LIBRARY}
)


MARK_AS_ADVANCED(
  LEARSDK_INCLUDE_DIR
  LEARVS_LIBRARY
  LEARLS_LIBRARY
  LEARMC_LIBRARY
  LEARSDEE_LIBRARY
  LEAROSSTOED_LIBRARY
  LEARDOT3_LIBRARY
 )
