
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the JavaScriptGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */

		
	
		
			
// namespace tmx.TmxLog
			
var utils = {
	LogLevel : {
		logERROR : 
		{								
				value  : 0,
				string : 'ERROR'
		},
		logWARNING : 
		{								
				value  : 1,
				string : 'WARNING'
		},
		logINFO : 
		{								
				value  : 2,
				string : 'INFO'
		},
		logDEBUG : 
		{								
				value  : 3,
				string : 'DEBUG'
		},
		logDEBUG1 : 
		{								
				value  : 4,
				string : 'DEBUG1'
		},
		logDEBUG2 : 
		{								
				value  : 5,
				string : 'DEBUG2'
		},
		logDEBUG3 : 
		{								
				value  : 6,
				string : 'DEBUG3'
		},
		logDEBUG4 : 
		{								
				value  : 7,
				string : 'DEBUG4'
		}
	}
};

Object.freeze(utils);
	
		
	
